<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <!--Test project specific area-->
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleTables" Version="2.6.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="MSTest" Version="3.10.4" />
        <PackageReference Include="Solution.Parser" Version="3.0.3" />
    </ItemGroup>
</Project>